export const MODULE_NAME_DATABASE_SERVICE = 'dataBaseService'
export const MODULE_NAME_LOGIN = 'login'
export const MODULE_NAME_NOTIFY = 'notifier'
export const MODULE_NAME_DATA_SERVICE = 'dataService'
export const MODULE_NAME_HTTP_SERVICE = 'httpService'
