export const WebServer = [
  {errorCode: '200'}, {desc: '操作成功'},
  {errorCode: '301'}, {desc: '登录鉴权失败，用户名或密码错误'},
  {errorCode: '302'}, {desc: '该账号被锁定，不能登录'},
  {errorCode: '303'}, {desc: '该账号已存在'},
  {errorCode: '304'}, {desc: '临时用户该账号已过期'},
  {errorCode: '305'}, {desc: '该账户连续多次密码输入错误，限制登录'},
  {errorCode: '401'}, {desc: 'Token过期'},
  {errorCode: '501'}, {desc: '无权限操作'},
  {errorCode: '502'}, {desc: '文件或目录不存在'},
  {errorCode: '503'}, {desc: 'OSS鉴权失败，无权限上传或下载文件'},
  {errorCode: '504'}, {desc: ''},
  {errorCode: '601'}, {desc: '其他业务错误'},
  {errorCode: '602'}, {desc: '文件上传失败'},
  {errorCode: '603'}, {desc: '获取uploadId失败'},
  {errorCode: '604'}, {desc: '个人云盘容量不够'},
  {errorCode: '605'}, {desc: '文件名重复（文件和文件夹重名不算重复）'},
  {errorCode: '606'}, {desc: '目录中的文件夹数量已经达到或超过100个'},
  {errorCode: '607'}, {desc: '系统繁忙（前端要重试，有可能发生在：add、delete、checkExist操作中）'},
  {errorCode: '608'}, {desc: '文件名不合法'},
  {errorCode: '609'}, {desc: '分片上传异常'},
  {errorCode: '701'}, {desc: '账号已在其它地方登录'},
  {errorCode: '801'}, {desc: '目录结构已经变化，不可再续传'},
  {errorCode: '802'}, {desc: '移动或复制时，目标目录有重名文件或文件夹'},
  {errorCode: '803'}, {desc: '文件正在转码，请稍后再试'},
  {errorCode: '804'}, {desc: '非法的目标路径 对应文件索引2004'},
  {errorCode: '805'}, {desc: '操作不支持（如复制文件夹）对应索引2005'},
  {errorCode: '901'}, {desc: '该群主下存在群组，不能删除'},
  {errorCode: '902'}, {desc: '该用户已是群主，不能重复添加'},
  {errorCode: '903'}, {desc: '请先将该用户添加为群主'},
  {errorCode: '904'}, {desc: '群组名称已存在'},
  {errorCode: '905'}, {desc: '提取密码不正确'},
  {errorCode: '906'}, {desc: '该分享不支持取消'},
  {errorCode: '907'}, {desc: '提取密码不能为空'},
  {errorCode: '908'}, {desc: '该用户已是部门管理员，不可重复添加'},
  {errorCode: '909'}, {desc: '分享已被取消'},
  {errorCode: '910'}, {desc: '请先解锁部门'},
  {errorCode: '911'}, {desc: '超过有效期，链接不能访问'},
  {errorCode: '912'}, {desc: '超过下载次数，不能下载'},
  {errorCode: '913'}, {desc: '验证码错误'},
  {errorCode: '914'}, {desc: '需要输入验证码'}
]

export const UCServer = [
  {errorCode: '0'}, {desc: '操作成功'},
  {errorCode: '301'}, {desc: '鉴权失败，用户名或密码错误'},
  {errorCode: '501'}, {desc: '密码解密失败'},
  {errorCode: '503'}, {desc: '服务未授权'},
  {errorCode: '601'}, {desc: '业务错误'}
]

export const GroupServer = [
  {errorCode: '0'}, {desc: '操作成功'},
  {errorCode: '302'}, {desc: '该用户被锁定，不能登录'},
  {errorCode: '303'}, {desc: '账号已存在'},
  {errorCode: '501'}, {desc: '无权限操作'},
  {errorCode: '503'}, {desc: '服务未授权'},
  {errorCode: '601'}, {desc: '业务错误'},
  {errorCode: '901'}, {desc: '该群主下存在群组，不能删除'},
  {errorCode: '902'}, {desc: '该用户已是群主，不能重复添加'},
  {errorCode: '903'}, {desc: '请先将该用户添加为群主'},
  {errorCode: '904'}, {desc: '群组名称已存在'},
  {errorCode: '905'}, {desc: '提取密码不正确'},
  {errorCode: '906'}, {desc: '该分享不支持取消'},
  {errorCode: '907'}, {desc: '提取密码不能为空'},
  {errorCode: '908'}, {desc: '该用户已是部门管理员，不可重复添加'},
  {errorCode: '909'}, {desc: '分享已被取消'},
  {errorCode: '910'}, {desc: '请先解锁部门'},
  {errorCode: '911'}, {desc: '超过有效期，链接不能访问'},
  {errorCode: '912'}, {desc: '超过下载次数，不能下载'}
]
